name: dandelinux build test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        run:  curl -fsSL https://test.docker.com -o test-docker.sh & sudo sh test-docker.sh
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Docker Container
        run: ./local.sh
