name: dandelinux build test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore

runs:
  using: 'docker'
  image: 'Dockerfile'
