name: dandelinux build test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .gitignore
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run Docker Container
        run: ./local.sh
